## CS559: Homework #1-1

This is a part of Assignment #1 and this assignment is due on **9/16/2020 by 11:59 PM**. You are going to submit the assignment both in format of *ipynb* and *html*. The assignment should be own work and must not be shared between classmates. Try to avoid using built-in functions. 

This assignment is about linear algebra and is more focusing on implementing functions. 

### Problem 1
- Write a function `dot_product` to calculate the dot product of two 1 by n arrays. 
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [3]:
def dot_product(a, b):
    if len(a) != len(b):
        return "Not Valid Input"
    sum = 0
    for i in range(len(a)):
        sum += a[i] * b[i]
    return sum
dot_product([1,2,3,4],[2,3,4,5])


40

- Test your code after generating two random 1 by 10 arrays. 

In [4]:
import numpy as np
a = np.random.randint(low=1, high=100, size=10)
b = np.random.randint(low=1, high=100, size=10)
dot_product(a, b)
np.dot(a,b) == dot_product(a,b)

True

- Consider three vectors ${\bf x}_1=(1,3), {\bf x}_2=(-1,5)$, and ${\bf x}_3=(0,7)$. 

    - Find the distance of each point from the origin.

    - Find the center of three points. 

    - Rotate the coordinates by 35 degress in counter clockwise. 

    - Magnify the area by 4 times. 

In [40]:
### Code Starts Here
import math
def distance_from_origin(x):
    return math.sqrt(x[0] * x[0] + x[1] * x[1])

def center(x,y,z):
    return [(x[0] + y[0] + z[0])/3, (x[1] + y[1] +z[1])/3]

def rotate(x):
    return [x[0] * math.cos(math.radians(35)) - x[1] * math.sin(math.radians(35)), x[0] * math.sin(math.radians(35)) + x[1] * math.cos(math.radians(35))]

def area(x,y,z):
    return 2 * abs(x[0]*(y[1] - z[1]) + y[0]*(z[1] - x[1]) + z[0]*(x[1] - y[1]))

x = [1,3]
y = [-1, 5]
z = [0, 7]
print(distance_from_origin(x))
print(distance_from_origin(y))
print(distance_from_origin(z))
print(center(x,y,z))
print(rotate(x))
print(rotate(y))
print(rotate(z))
print(area(x,y,z))


3.1622776601683795
5.0990195135927845
7.0
[0.0, 5.0]
[-3.0, 1.0000000000000002]
[-5.0, -0.9999999999999997]
[6.123233995736766e-17, 1.0]
[-7.0, 4.286263797015736e-16]
12


### Problem 2
- Write a function `mat_product` to calculate the matrix product of two n by n arrays. For example:


$A = \begin{bmatrix} 1 & 3 & 0 \\ 2 & 0 & 2 \\ 1 & 1 & 4 \end{bmatrix}$ and $A\cdot A=\begin{bmatrix} 7 & 3 & 6 \\ 4 & 8 & 8 \\ 7 & 8 & 18 \end{bmatrix}$

In [6]:
### Code Starts Here
def column(x, num):
    return [x[i][num] for i in range(len(x))]
def mat_product(x, y):
    z = []
    for i in range(len(x)):
        z.append([])
        for j in range(len(x)):
            z[i].append(dot_product(x[i], column(y, j)))
    return z
x = [[1,3,0],[2,0,2],[1,1,4]]
mat_product(x,x)

[[7, 3, 6], [4, 8, 8], [7, 7, 18]]

Test your code after generating two random 4 by 4 matrices, ${\bf X}$ and ${\bf Y}$.  

In [7]:
### Test Starts Here
x = []
z = []
for i in range(4):
    x.append(np.random.randint(low=1, high=100, size=4))
    z.append(np.random.randint(low=1, high=100, size=4))
x
z
mat_product(x, z)
np.matmul(x,z) == mat_product(x,z)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

- Transpose ${\bf X}$ and use the `mat_product` function to find the matrice of product: $Z={\bf X}^T\cdot{\bf Y}$

In [30]:
### Code Starts Here
def transpose(x):
    z = []
    for i in range(len(x[0])):
        z.append(column(x, i))
    return z

x = [[1,3,0],[2,0,2],[1,1,4]]
mat_product(transpose(x),x)

[[6, 4, 8], [4, 10, 4], [8, 4, 20]]

### Problem 3
- Write a function, `Det`, to find the determinant of n by n matrice, `EGval`, that finds the eigenvalue $\lambda$ and a function, `EGvec`, that finds the eigenvectors ${\bf x}$
- For the confirmation, use ${\bf A}=\begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}$.

In [17]:
### Det Code Starts Here ###
a = [[1,2],[2,4]]
determinant = a[0][0]*a[1][1] - a[0][1]*a[1][0]
determinant
np.linalg.det(a) == determinant

True

In [16]:
### EGval Code Starts Here ###
#det(a - 𝜆I) = 0
#det([[1-𝜆,2],[2,4-𝜆]) = 0
#4 - 5𝜆 + 𝜆^2 - 4 = 0
#-5𝜆 + 𝜆^2 = 0
#𝜆^2 - 5𝜆 = 0
#𝜆 = 0 or 𝜆 = 5
np.linalg.eig(a)[0] == [0,5]

<ipython-input-16-e7af9db7871b>:8: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.linalg.eig(a)[0] == [0,5]


False

In [18]:
### EGvec Code Starts Here ###
#𝜆 = 0
#[[1,2],[2,4]] * [x,y] = 0
#[[1,2],[0,0]] * [x,y] = 0
#x1 = [-2,1]
#𝜆 = 5
#[[-4,2],[2,-1]] * [x,y] = 0
#[[-2,1],[0,0]] * [x,y] = 0
#x2 = [1,2]

np.linalg.eig(a)

(array([0., 5.]),
 array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))